export const PERP_MARKETS = [
  {
    symbol: "SOL-PERP",
    baseAsset: "SOL",
    marketIndex: 0,
    minOrderSize: 0.1,
    tickSize: 0.001,
    geckoPool: "8sLbNZoA1cfnvMJLPfp98ZLAnFSYCFApfJKMbiXNLwxj",
    tvSymbol: "BINANCE:SOLUSDT",
    category: ["L1", "Solana"],
  },
  {
    symbol: "BTC-PERP",
    baseAsset: "BTC",
    marketIndex: 1,
    minOrderSize: 0.0001,
    tickSize: 1,
    geckoPool: "4nFbdT7DeXATvaRZfR3WqALGJnogMjqe9vf2H6C1WXBr",
    tvSymbol: "BINANCE:BTCUSDT",
    category: ["L1", "Payment"],
  },
  {
    symbol: "ETH-PERP",
    baseAsset: "ETH",
    marketIndex: 2,
    minOrderSize: 0.01,
    tickSize: 0.01,
    geckoPool: "4yrHms7ekgTBgJg77zJ33TsWrraqHsCXDtuSZqUsuGHb",
    tvSymbol: "BINANCE:ETHUSDT",
    category: ["L1", "Infra"],
  },
  {
    symbol: "APT-PERP",
    baseAsset: "APT",
    marketIndex: 3,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:APTUSDT",
    category: ["L1"],
  },
  {
    symbol: "1MBONK-PERP",
    baseAsset: "1MBONK",
    marketIndex: 4,
    minOrderSize: 1,
    tickSize: 0.0001,
    geckoPool: "",
    tvSymbol: "BINANCE:BONKUSDT",
    category: ["Meme", "Solana"],
  },
  {
    symbol: "POL-PERP",
    baseAsset: "POL",
    marketIndex: 5,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:POLUSDT",
    category: ["L2"],
  },
  {
    symbol: "ARB-PERP",
    baseAsset: "ARB",
    marketIndex: 6,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:ARBUSDT",
    category: ["L2"],
  },
  {
    symbol: "DOGE-PERP",
    baseAsset: "DOGE",
    marketIndex: 7,
    minOrderSize: 10,
    tickSize: 0.0001,
    geckoPool: "",
    tvSymbol: "BINANCE:DOGEUSDT",
    category: ["Meme", "Dog"],
  },
  {
    symbol: "BNB-PERP",
    baseAsset: "BNB",
    marketIndex: 8,
    minOrderSize: 0.01,
    tickSize: 0.1,
    geckoPool: "",
    tvSymbol: "BINANCE:BNBUSDT",
    category: ["Exchange"],
  },
  {
    symbol: "SUI-PERP",
    baseAsset: "SUI",
    marketIndex: 9,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:SUIUSDT",
    category: ["L1"],
  },
  {
    symbol: "1MPEPE-PERP",
    baseAsset: "1MPEPE",
    marketIndex: 10,
    minOrderSize: 1,
    tickSize: 0.0001,
    geckoPool: "",
    tvSymbol: "BINANCE:PEPEUSDT",
    category: ["Meme"],
  },
  {
    symbol: "OP-PERP",
    baseAsset: "OP",
    marketIndex: 11,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:OPUSDT",
    category: ["L2"],
  },
  {
    symbol: "RENDER-PERP",
    baseAsset: "RENDER",
    marketIndex: 12,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:RENDERUSDT",
    category: ["Infra", "Solana"],
  },
  {
    symbol: "XRP-PERP",
    baseAsset: "XRP",
    marketIndex: 13,
    minOrderSize: 1,
    tickSize: 0.0001,
    geckoPool: "",
    tvSymbol: "BINANCE:XRPUSDT",
    category: ["Payments"],
  },
  {
    symbol: "INJ-PERP",
    baseAsset: "INJ",
    marketIndex: 15,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:INJUSDT",
    category: ["L1", "Exchange"],
  },
  {
    symbol: "LINK-PERP",
    baseAsset: "LINK",
    marketIndex: 16,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:LINKUSDT",
    category: ["Oracle"],
  },
  {
    symbol: "PYTH-PERP",
    baseAsset: "PYTH",
    marketIndex: 18,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BYBIT:PYTHUSDT",
    category: ["Oracle", "Solana"],
  },
  {
    symbol: "TIA-PERP",
    baseAsset: "TIA",
    marketIndex: 19,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:TIAUSDT",
    category: ["Data"],
  },
  {
    symbol: "JTO-PERP",
    baseAsset: "JTO",
    marketIndex: 20,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:JTOUSDT",
    category: ["MEV", "Solana"],
  },
  {
    symbol: "SEI-PERP",
    baseAsset: "SEI",
    marketIndex: 21,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:SEIUSDT",
    category: ["L1"],
  },
  {
    symbol: "AVAX-PERP",
    baseAsset: "AVAX",
    marketIndex: 22,
    minOrderSize: 0.1,
    tickSize: 0.01,
    geckoPool: "",
    tvSymbol: "BINANCE:AVAXUSDT",
    category: ["L1"],
  },
  {
    symbol: "WIF-PERP",
    baseAsset: "WIF",
    marketIndex: 23,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:WIFUSDT",
    category: ["Meme", "Dog", "Solana"],
  },
  {
    symbol: "JUP-PERP",
    baseAsset: "JUP",
    marketIndex: 24,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:JUPUSDT",
    category: ["Exchange", "Solana"],
  },
  {
    symbol: "TAO-PERP",
    baseAsset: "TAO",
    marketIndex: 26,
    minOrderSize: 0.01,
    tickSize: 0.1,
    geckoPool: "",
    tvSymbol: "BINANCE:TAOUSDT",
    category: ["AI"],
  },
  {
    symbol: "W-PERP",
    baseAsset: "W",
    marketIndex: 27,
    minOrderSize: 1,
    tickSize: 0.001,
    geckoPool: "",
    tvSymbol: "BINANCE:WUSDT",
    category: ["Bridge"],
  },
];
